[all_follow]
nixpkgs = "nixpkgs"

[inputs.nixpkgs]
url = "https://channels.nixos.org/nixos-unstable/nixexprs.tar.xz"

[inputs.swash]
url = "github:ItsLemmy/swash"

[inputs.home-manager]
url = "github:nix-community/home-manager"

[inputs.nvf]
url = "github:notashelf/nvf"

[inputs.nix-darwin]
url = "github:nix-darwin/nix-darwin"

[inputs.zen-browser]
url = "github:youwen5/zen-browser-flake"
