color0 #55414c
color1 #ffb4ab
color2 #ffade1
color3 #ffade1
color4 #ffb4a5
color5 #ffade1
color6 #ffade1
color7 #f2dde7
color8 #a28a97
color9 #ffb4ab
color10 #ffade1
color11 #ffade1
color12 #ffb4a5
color13 #ffade1
color14 #ffade1
color15 #f2dde7

cursor                #f2dde7
cursor_text_color     #1b1017
background            #1b1017
foreground            #f2dde7
selection_foreground  #dabfcd
selection_background  #55414c
active_border_color   #ffade1
inactive_border_color #55414c
url_color             #ffade1

active_tab_foreground   #5f004d
active_tab_background   #ffade1
inactive_tab_foreground #dabfcd
inactive_tab_background #55414c
cursor_trail_color      #dabfcd
